version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    ECR_URI: 199472244724.dkr.ecr.us-east-1.amazonaws.com/iot-backend
  # needed so Docker can run inside CodeBuild
  privileged: true

phases:
  pre_build:
    commands:
      - echo "Logging in to ECR"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION \
        | docker login --username AWS --password-stdin $ECR_URI
      - IMAGE_TAG=$(date +%Y%m%d%H%M%S)          # e.g. 20250525093010
  build:
    commands:
      - echo "Building NestJS image $IMAGE_TAG"
      - docker build -t iot-backend:$IMAGE_TAG .
      - docker tag iot-backend:$IMAGE_TAG $ECR_URI:$IMAGE_TAG
      - docker tag iot-backend:$IMAGE_TAG $ECR_URI:latest
  post_build:
    commands:
      - echo "Pushing images to ECR"
      - docker push $ECR_URI:$IMAGE_TAG
      - docker push $ECR_URI:latest

artifacts: { files: [] }   # nothing to export; images live in ECR
